dbt_airbnb:               #profile name, matches the profile: setting in dbt_project.yml
  target: prod             # Which target to load for this profile. Targets are defined in the
  outputs:                # Dictionary of connection configurations, one per target
    dev:                  # Target name, referenced by the `target` key above
      type: mysql         # The type of database. dbt uses this to determine which adapter to use. DBT needs to be installed with the adapter for this database, e.g. dbt-mysql
      server: "{{ env_var('DBT_MYSQL_SERVER') }}"  # Hostname or IP address of the MySQL server, defaulting to localhost if the environment variable is not set
      port: 3306
      schema: "{{ env_var('DBT_ENV_SCHEMA') }}"      # logical "schema", maps to database in many mysql adapters
      #database: airbnb   # not needed for mysql, but some adapters require both schema and database, so we include it for consistency with other profiles
      username: "{{ env_var('DBT_MYSQL_AIRBNB_USER') }}"
      password: "{{ env_var('DBT_MYSQL_AIRBNB_PASSWORD') }}"
      ssl_disabled: true
      threads: 1          # Default is one, I kept it same due to runing docker on other threads
    prod: # Target name, referenced by the `target` key above
      type: mysql         # The type of database. dbt uses this to determine which adapter to use. DBT needs to be installed with the adapter for this database, e.g. dbt-mysql
      server: "{{ env_var('DBT_MYSQL_SERVER') }}"  # Hostname or IP address of the MySQL server, defaulting to localhost if the environment variable is not set
      port: 3306
      schema: "{{ env_var('DBT_ENV_SCHEMA') }}"      # logical "schema", maps to database in many mysql adapters
      #database: airbnb   # not needed for mysql, but some adapters require both schema and database, so we include it for consistency with other profiles
      username: "{{ env_var('DBT_MYSQL_AIRBNB_USER') }}"
      password: "{{ env_var('DBT_MYSQL_AIRBNB_PASSWORD') }}"
      ssl_disabled: true
      threads: 1

# Above, is a production env setup where the sensitive information is not put it in plain text, rather being fetched from
# environment variables. You can set the environment variables in your local .env file or export them in your terminal
# session before running dbt commands.